export const LOGIN = 'LOGIN';
export const LOGOUT = 'LOGOUT';
export const DISPLAY_NOTIFICATION = 'DISPLAY_NOTIFICATION';
export const HIDE_NOTIFICATION = 'HIDE_NOTIFICATION';
export const GET_MY_CITIES = 'GET_MY_CITIES';
export const REMOVE_MY_CITIES = 'REMOVE_MY_CITIES';
export const SET_LOADING = 'SET_LOADING';
